### PR TITLE
fix: redirect after board is deleted

### LINKED ISSUE #3097: Automatically transition to landingpage
At the moment when the board owner deleted the board all the participants are still there. They should get transferred back zu our landingpage + toast (board has deleted).

### PR DESCRIPTION
**Pull request by Resaki1**
## Description

When a board is deleted, all users on the board are now redirected to the homepage including a toast. Closes #3097 

## Changelog

- added redirect to homepage
- when opening the homepage after board deletion, a toast is shown

### CODE REVIEW

File: src/store/middleware/board.tsx [hunk 1]
```diff
@@ -39,6 +39,7 @@ export const passBoardMiddleware = (stateAPI: MiddlewareAPI<Dispatch, Applicatio
 
         if (message.type === "BOARD_DELETED") {
           store.dispatch(Actions.leaveBoard());
+          window.location.assign("/?boardDeleted=true");
```
Comment (brandstetterm) [inline src/store/middleware/board.tsx:42]: Why don't you dispatch the board deleted toast here?

Comment (Resaki1) [reply src/store/middleware/board.tsx:42]: Because the toast disappears as soon as the redirect is finished

File: src/routes/Homepage/Homepage.tsx [hunk 2]
```diff
@@ -31,6 +33,16 @@ export const Homepage = withTranslation()(() => {
     dispatch(Actions.signOut());
   };
 
+  useEffect(() => {
+    const boardDeleted = new URLSearchParams(window.location.search).get("boardDeleted");
+
+    if (boardDeleted) {
+      Toast.error({
```
Comment (brandstetterm) [inline src/routes/Homepage/Homepage.tsx:40]: This should be an info toast and not an error toast I guess.

Comment (Resaki1) [reply src/routes/Homepage/Homepage.tsx:40]: Now that you say that, I think it should be the new deletion toast from #3121, shouldn't it?

Comment (brandstetterm) [reply src/routes/Homepage/Homepage.tsx:40]: No, it's a simple information for the participants that the board they have been on has been deleted. 

The deletion toast would be for the moderator that has deleted the board.

File: public/locales/de/translation.json [hunk 3]
```diff
@@ -389,6 +389,7 @@
     "serverConnection": "Der Server ist leider nicht erreichbar. Bitte versuche die Seite neu zu laden.",
     "retry": "Wiederholen",
     "joinBoard": "Es tut uns leid, aber wir haben ein Problem beim Beitreten des Boards. Bitte versuche es erneut.",
+    "boardDeleted": "Das Board wurde gelöscht! Du wirst zur Startseite weitergeleitet.",
```
Comment (brandstetterm) [inline public/locales/de/translation.json:392]:
```suggestion
    "boardDeleted": "Das Board wurde gelöscht! Du wurdest zur Startseite weitergeleitet.",
```
