### PR TITLE
Fix column edit by toggleing the column edit mode only for moderators on `onDoubleClick` event

### LINKED ISSUE #2453: Regular participants should not be able to edit column name (by double click)

### PR DESCRIPTION
**Pull request by brandstetterm**
Closes #2453

### CODE REVIEW

File: src/components/Column/Column.tsx [hunk 1]
```diff
@@ -100,7 +100,14 @@ export const Column = ({id, name, color, visible, index}: ColumnProps) => {
     columnNameMode === "VIEW" ? (
       <div className={classNames("column__header-text-wrapper", {"column__header-text-wrapper--hidden": !visible})}>
         {!visible && <HiddenIcon className="column__header-hidden-icon" title={t("Column.hiddenColumn")} onClick={toggleVisibilityHandler} />}
-        <h2 onDoubleClick={() => setColumnNameMode("EDIT")} className={classNames("column__header-text", {"column__header-text--hidden": !visible})}>
+        <h2
+          onDoubleClick={() => {
+            if (isModerator) {
+              setColumnNameMode("EDIT");
```
Comment (bitionaire) [inline src/components/Column/Column.tsx:106]: Your PR fixes the use but I don't like the `setColumnNameMode` function. It can only be one of `VIEW` or `EDIT` and therefore of type `boolean`. :)
You can leave it there for now though.

**Review by bitionaire — APPROVED** [review]
