### PR TITLE
fix: proper Icon for note deletion toast

### LINKED ISSUE #3095: Wrong toast by deleted note
The toast should show the trash icon not the error icon.

### PR DESCRIPTION
**Pull request by Resaki1**
## Description

Changed the toast upon note deletion from the previous error toast to a new toast with a trash icon. Closes #3095 

## Changelog

- added new deletion toast with trash icon
- changed note deletion toast from error to deletion

## Visual Changes

Bildschirmfoto 2023-06-20 um 16 22 59

### CODE REVIEW

File: src/utils/Toast.tsx [hunk 1]
```diff
@@ -152,8 +153,54 @@ function info(options: Options) {
...
+ * @param options.hintMessage An optional hint message to display in the toast notification.
+ * @param options.hintOnClick An optional callback function to execute when the hint message/checkbox is clicked.
+ * @param options.buttons An array of button-labels to display in the toast notification. (for e.g. ["Save", "Cancel"])
+ * @param options.firstButtonOnClick An optional callback function to execute when the first button is clicked.
+ * @param options.secondButtonOnClick An optional callback function to execute when the second button is clicked.
+ * @param options.autoClose The time in milliseconds after which the toast notification should automatically close.
+ * @param options.icon An optional icon to display in the toast notification.
+ * @param options.iconName An optional icon Name. Needs to be set to a any different name than "success", "error", or "info" when an icon is passed aswell.
+ */
+function deletion(options: Options) {
```
Comment (brandstetterm) [inline src/utils/Toast.tsx:171]: It would be kinda cool to make it less specific and have a generic `custom(...)` which you can give a custom icon over the options as ReactNode

**Review by brandstetterm — APPROVED** [review]
