### PR TITLE
Improved note stack animation and fixed drag preview

### LINKED ISSUE #2292: Remove ugly corner borders of dragged note
Image

Look at this

### PR DESCRIPTION
**Pull request by Resaki1**
## Description

Improved the note stack animation by hinting to where the dropped note/stack will be in the new stack. It's been implemented with a future setting in mind, which will let users change their preferred sorting method. Also fixes the drag preview on mobile devices and the ugly border of the drag preview (therefore closes #2292).

## Changelog

- created custom drag layer to be able to set the z-index of the drag-preview
- created custom drag-preview for the new drag-layer
- added three animations depending on a variable, which can be changed to the sort setting in state once implemented
- removed drop hover animation if note is dragged over its original position

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### Previous animation and drag preview:

https://user-images.githubusercontent.com/35272402/205017351-244751ac-64e1-473e-92dc-6ecaaf65b9d9.mov

### New animation, stack below parent but above other notes in stack (current setting):

https://user-images.githubusercontent.com/35272402/205017659-2628e60e-d79e-42e0-a400-591513a82a58.mov

### New animation, stack above:

https://user-images.githubusercontent.com/35272402/205017890-326f276c-46dc-42d8-9c67-40cc152fcdc1.mov

### New animation, stack below:

https://user-images.githubusercontent.com/35272402/205018160-4ab1efbc-7a15-4fac-b8ca-d3977cd1b603.mov

### CODE REVIEW

File: src/components/Note/Note.tsx [hunk 1]
```diff
@@ -93,9 +98,17 @@ export const Note = (props: NoteProps) => {
   drag(noteRef);
   drop(noteRef);
 
+  // TODO: replace with stack setting from state when implemented. thanks, love u <3
```
Comment (brandstetterm) [inline src/components/Note/Note.tsx:101]: love you too

File: src/components/Note/Note.tsx [hunk 2]
```diff
@@ -93,9 +98,17 @@ export const Note = (props: NoteProps) => {
...
+  const stackSetting: "stackOntop" | "stackBetween" | "stackBelow" = "stackBetween";
```
Comment (brandstetterm) [inline src/components/Note/Note.tsx:102]: I guess best default case would be "stackBelow"

**Review by brandstetterm — APPROVED** [review]
